updateComment: true

before: "✨ Good work on this PR so far! Unfortunately, the [{{ provider }} build]({{ targetUrl }}) is failing as of {{ commit }}. Here's the output:"

after: "I'm sure you can fix it! If you need help, don't hesitate to ask a maintainer of the project!"
