name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    strategy:
      matrix:
        node-version: [12]
        platform: [ubuntu-latest, mac-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: |
          NODE_ENV= npm ci
          npm install -g codecov
      - name: Run Tests and publish code coverage
        run: |
          npm run test:coverage
          codecov -t ${{ secrets.CODECOV_TOKEN }}
      - name: Run Build
        run: npm run build
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
