name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    strategy:
      matrix:
        node-version: [12]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: Install packages
        run: |
          NODE_ENV= npm ci
          npm install -g codecov
      - name: Run Tests and publish code coverage
        run: |
          npm run test:coverage
          codecov -t ${{ secrets.CODECOV_TOKEN }}
      - name: Run Build
        run: npm run build
      - uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish package
        run: |
          bash scripts/release.sh
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
