name: CI

on: [push]

jobs:
  ci:
    strategy:
      matrix:
        node-version: [12]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Run Tests with coverage
        run: npm run test:coverage
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1.0.5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          yml: ./codecov.yml
#          fail_ci_if_error: true
      - name: Build
        run: npm run build
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
